### ISSUE TITLE
Tab completion damaged

### ISSUE THREAD

**Issue by FranklinYu** [apjanke/oh-my-zsh-custom#2]
If I have folder structure

```
foo
  bar
  baz
```

then when I type in `cd foo/z` and hit tab, it should give me `cd foo/baz`. This works with OMZ without OMZC.

**Comment by apjanke** [comment]
That's intentional. I've turned off some of the advanced completion support while I'm learning how to use and configure it. If you want completion to match inside words like that, restore the original `matcher-list` setting.

``` shell
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
```
